# Generated by Django 3.1.5 on 2021-01-21 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, unique=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('avatar', models.ImageField(upload_to='static/img/')),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(max_length=700)),
                ('data_added', models.TimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='News.category')),
            ],
        ),
    ]
